In [1]:
import numpy as np
from numpy import genfromtxt

In [3]:
data=genfromtxt('../DATA/bank_note_data.txt',delimiter=',')

In [4]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [6]:
labels=data[:,4]

In [10]:
labels   #

array([0., 0., 0., ..., 1., 1., 1.])

In [11]:
features=data[:,0:4]

In [12]:
features  #

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [13]:
#splitting our data into training and test set

In [14]:
X= features
y=labels

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.33, random_state=42)

In [21]:
len(X)

1372

In [22]:
len(X_train) #67% of data for training set

919

In [23]:
len(X_test)  #33% for test 

453

In [24]:
#Forcing all our feature data to fall within certain range

In [26]:
from sklearn.preprocessing import MinMaxScaler

In [27]:
scaler_object= MinMaxScaler()

In [28]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [29]:
scaled_X_train=scaler_object.transform(X_train)

In [31]:
scaled_X_test=scaler_object.transform(X_test)

In [32]:
scaled_X_train.max()

1.0000000000000002

In [35]:
scaled_X_train.min()

0.0

In [36]:
#Building a simple network with keras

In [37]:
from keras.models import Sequential
from keras.layers import Dense

In [38]:
model = Sequential()

In [39]:
model.add(Dense(4, input_dim=4, activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(1, activation='sigmoid'))

In [40]:
#metrics for model

In [43]:
model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])

In [46]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
 - 0s - loss: 0.0714 - acc: 0.9869
Epoch 2/50
 - 0s - loss: 0.0703 - acc: 0.9891
Epoch 3/50
 - 0s - loss: 0.0696 - acc: 0.9880
Epoch 4/50
 - 0s - loss: 0.0678 - acc: 0.9891
Epoch 5/50
 - 0s - loss: 0.0664 - acc: 0.9946
Epoch 6/50
 - 0s - loss: 0.0655 - acc: 0.9913
Epoch 7/50
 - 0s - loss: 0.0650 - acc: 0.9913
Epoch 8/50
 - 0s - loss: 0.0637 - acc: 0.9913
Epoch 9/50
 - 0s - loss: 0.0621 - acc: 0.9946
Epoch 10/50
 - 0s - loss: 0.0606 - acc: 0.9946
Epoch 11/50
 - 0s - loss: 0.0595 - acc: 0.9956
Epoch 12/50
 - 0s - loss: 0.0585 - acc: 0.9956
Epoch 13/50
 - 0s - loss: 0.0585 - acc: 0.9946
Epoch 14/50
 - 0s - loss: 0.0558 - acc: 0.9956
Epoch 15/50
 - 0s - loss: 0.0545 - acc: 0.9946
Epoch 16/50
 - 0s - loss: 0.0534 - acc: 0.9956
Epoch 17/50
 - 0s - loss: 0.0523 - acc: 0.9956
Epoch 18/50
 - 0s - loss: 0.0517 - acc: 0.9956
Epoch 19/50
 - 0s - loss: 0.0504 - acc: 0.9956
Epoch 20/50
 - 0s - loss: 0.0492 - acc: 0.9956
Epoch 21/50
 - 0s - loss: 0.0485 - acc: 0.9956
Epoch 22/50
 - 0s - lo

In [47]:
#Model is trained Now we'll test

In [49]:
#model.predict_classes(scaled_X_test)

In [50]:
model.metrics_names

['loss', 'acc']

In [51]:
from sklearn.metrics import confusion_matrix, classification_report

In [52]:
predictions=model.predict_classes(scaled_X_test)

In [53]:
confusion_matrix(y_test,predictions)

array([[256,   1],
       [  0, 196]], dtype=int64)

In [54]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00       257
        1.0       0.99      1.00      1.00       196

avg / total       1.00      1.00      1.00       453



In [55]:
model.save('bankmodel.h5')

In [58]:
#########################################################

In [59]:
from keras.models import load_model

In [60]:
newModel=load_model('bankmodel.h5')

In [ ]:
newModel.