In [2]:
import numpy as np


In [3]:
myList=[1,2,3]

In [4]:
type(myList)

list

In [5]:
#np.array(_array_)  converts any List to numpy array.

In [6]:
np.array(myList) #converts any list to numpy array.

array([1, 2, 3])

In [7]:
myArray=np.array(myList)

In [8]:
type(myArray)

numpy.ndarray

In [9]:
#np.arange(start,stop,step,dtype) Returns evenly sized spaced values with a given interval.

In [10]:
np.arange(0,10,2) # np.arange(0,10)

array([0, 2, 4, 6, 8])

In [11]:
#np.zeros(shape,dtype,order)

In [12]:
np.zeros(shape=(5,5)) #or np.zeros((5,5))  
# 5 rows by 5 columns  
# .'s' after 0 means that zeros are of type float, as by default np.zeros generate floats.

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
type(0)
type(0.)
type(.0)

float

In [21]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
myarray=np.ones((2,4))

In [36]:
#np.random.randint(10,100) returns 33 only single value,
np.random.randint(0,100,10) #returns 10 values

array([76, 95, 87,  0, 73,  8, 62, 36, 83, 99])

In [37]:
np.random.seed(101) #ti return same random no.'s' everytime
arr=np.random.randint(0,100,10)


In [38]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [39]:
arr2= np.random.randint(0,100,10)

In [40]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [41]:
arr2.max()

93

In [42]:
arr2.argmax() #returns index of the maximum value in array.

8

In [43]:
arr.min()

9

In [44]:
arr.argmin()

7

In [45]:
arr.mean()

60.8

In [49]:
arr.shape  #property , returns the shape of array 

(10,)

In [50]:
arr.reshape(2,5) #reshape the array

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [52]:
#arr.reshape(2,10) #gives error as dimensions does not make sense as we just have 10 elements and this is requiring 20

In [53]:
mat=np.arange(0,100).reshape(10,10)

In [63]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [64]:
mat.shape

(10, 10)

Getting single value from mat array.

In [72]:
row=0
col=1

In [73]:
mat[row,col]

1

In [74]:
mat[4,6]

46

In [ ]:
# : means all values.
# [:,2] means all rows of column 2.
# [2,:] means 2 row and all columns.

In [78]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [79]:
mat[1,:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [80]:
mat[1,:].shape

(10,)

In [82]:
mat[:,1].reshape(5,2)

array([[ 1, 11],
       [21, 31],
       [41, 51],
       [61, 71],
       [81, 91]])

In [85]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [86]:
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [87]:
#slicing

In [88]:
#slicing 3 * 3

In [90]:
mat[0:3,0:3] 

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [ ]:
#slicing 3*4 , this is normal python slicing ,how we slice string or etc.

In [91]:
mat[0:3,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [92]:
#copy

In [93]:
myNewMat=mat.copy()

In [94]:
myNewMat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [95]:
#from 0 to 6 row get all columns


In [104]:
myNewMat[0:6,:] # or myNewMat[:6,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [109]:
expMat=myNewMat[0:6,:].copy()

In [110]:
#from 0 to 6 row to all columns ,set to 0

In [111]:
expMat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [112]:
expMat[0:6,:] =0

In [113]:
expMat

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [114]:
myNewMat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [115]:
myNewMat[0:6,:]=999


In [116]:
myNewMat

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [118]:
# this is used to reassign some image pixels